name: CLI Integration Test

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cli-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Run CLI Integration Test
        run: ./scripts/test-cli-npx-integration.sh 